# Generated by Django 3.2.6 on 2021-08-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AlterField(
            model_name='activity',
            name='route_type',
            field=models.CharField(max_length=50),
        ),
    ]
